"""meters and meter_data

Revision ID: 376fd820428a
Revises: 
Create Date: 2018-04-02 15:13:44.399545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '376fd820428a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meters_label'), 'meters', ['label'], unique=True)
    op.create_table('meter_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meter_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meter_data_timestamp'), 'meter_data', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meter_data_timestamp'), table_name='meter_data')
    op.drop_table('meter_data')
    op.drop_index(op.f('ix_meters_label'), table_name='meters')
    op.drop_table('meters')
    # ### end Alembic commands ###
